name: store_sync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  shared_preferences: ^2.2.2

  fl_chart: ^0.68.0

  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # HTTP for API communication
  http: ^1.2.0

  # Image Picker for selecting images
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.8
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive code generator
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/store_logo.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/store_logo2.png
    - assets/images/store_logo3.png

  fonts:
    - family: OpenSans Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: OpenSans Italic
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf

    - family: OpenSans Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
